apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template: # former pod template yaml
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  # selector:
  #   app: myapp
  #   type: front-end
# kubeclt create -f rc-definition.yaml
# kubectl get replicationcontroller
