apiVersion: v1
kind: Pod
metadata:
  name: mynginx-pod
  labels:
    app: myapp
spec:
  containers:
    - name: mynginx
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
